#!/bin/sh /etc/rc.common

START=60
STOP=60
APP='chinadns'
DNSMASQ_CONF='/etc/dnsmasq.conf'
DNSMASQ_CHINADNS_CONF='/etc/dnsmasq.chinadns.conf'
iplist_file='/etc/ipset/spurious'
chnroute_file='/etc/ipset/cdn'

config_load "$APP"
local enabled dnsmasq_enabled address port dns_server
config_get enabled config enabled
config_get dnsmasq_enabled config dnsmasq_enabled '0'
config_get address config address '0.0.0.0'
config_get port config port '5353'
config_get dns_server config dns_server '114.114.114.114,208.67.222.222,8.8.8.8'

update_chnroute_file() {
    curl 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | grep ipv4 | grep CN | awk -F\| '{ printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > $chnroute_file
}

dnsmasq_chinadns_start() {
    [ -f $DNSMASQ_CHINADNS_CONF ] || {
        [ -z $(cat $DNSMASQ_CONF | grep "^conf-file=$DNSMASQ_CHINADNS_CONF") ] && {
            echo "conf-file="$DNSMASQ_CHINADNS_CONF >>$DNSMASQ_CONF
        } 
        echo -e "no-resolv\nserver=127.0.0.1#"$port >$DNSMASQ_CHINADNS_CONF
        /etc/init.d/dnsmasq restart
    }
}

dnsmasq_chinadns_stop() {
    [ -f $DNSMASQ_CHINADNS_CONF ] && {
        DNSMASQ_CHINADNS_CONF_SED=$(echo $DNSMASQ_CHINADNS_CONF | sed 's/\//\\\//g' )
        sed -i "/^conf-file=$DNSMASQ_CHINADNS_CONF_SED/d" $DNSMASQ_CONF
        rm -f $DNSMASQ_CHINADNS_CONF
        /etc/init.d/dnsmasq restart
    }
}

start() {
    [ "$1" = "update_chnroute_file" ] && update_chnroute_file

    [ "$enabled" = '1' ] || return 1

    service_start /usr/bin/chinadns \
    -b $address \
    -p $port \
    -s $dns_server \
    -l $iplist_file \
    -c $chnroute_file & sleep 1

    if [ "$dnsmasq_enabled" = '1' ];
        then
        dnsmasq_chinadns_start
    else {
        dnsmasq_chinadns_stop
        iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports $port
    }
    fi
}

stop() {
    iptables -t nat -D PREROUTING -p udp --dport 53 -j REDIRECT --to-ports $port
    dnsmasq_chinadns_stop
    service_stop /usr/bin/chinadns
}

